//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fp_fx_conversion_gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fp_fx_conversion_gui.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module fixed_to_ieeefp(fp_output, fx_input);
        ///
        ///	parameter FIXED_TOTAL_BIT = 8;
        ///	
        ///	input [FIXED_TOTAL_BIT-1:0] fx_input;
        ///	output [31:0] fp_output;
        ///	//Total input bit width = 32
        ///	wire fx_sign = fx_input[FIXED_TOTAL_BIT-1]; 
        ///	
        ///	//assign {fx_sign, fx_number[31:32-FIXED_TOTAL_BIT]} = fx_input;
        ///	
        ///	wire [31:0] fx_number;
        ///	
        ///	wire [22:0] fp_mantissa;
        ///	wire [7:0] fp_exp;
        ///	
        ///	wire [31:0] scaled_out;
        ///	wire [7:0] shift_amnt;
        ///	
        ///	wire [FIXED_TOTAL_BIT-2:0] fx_number_without_sign;
        ///	twos_complement tc(fx_n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fixed_to_float {
            get {
                return ResourceManager.GetString("fixed_to_float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module fixed_to_ieeefp_tb;
        ///
        ///	parameter FIXED_TOTAL_BIT = __TOTAL_BITS__;
        ///	reg [FIXED_TOTAL_BIT-1:0] fixed_in;
        ///	
        ///	wire [31:0] float_out;
        ///	
        ///	integer fileHandle, dummyHandle;
        ///	
        ///	initial begin
        ///		$dumpfile(&quot;float_to_fixed.vcd&quot;);
        ///		$dumpvars(0, v);
        ///	end
        ///	
        ///	integer fWriteHandle;
        ///	always @(float_out) begin
        ///		#5 $fwrite(fWriteHandle, &quot;%b:%b%b%b\n&quot;, fixed_in, float_out[31], float_out[30:23],float_out[22:0]);
        ///		//#5 $display(&quot;%b:%b%b%b\n&quot;, fixed_in, float_out[31], float_out[30:23],float_out[22:0]);    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fixed_to_float_tb {
            get {
                return ResourceManager.GetString("fixed_to_float_tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module ieeefp_to_fixed(fx_number,fp_input);
        ///
        ///	parameter FIXED_TOTAL_BIT = 8;
        ///	
        ///	//Total input bit width = 32
        ///	input [31:0] fp_input;
        ///	wire fx_sign;
        ///	output [FIXED_TOTAL_BIT-1:0] fx_number;
        ///	
        ///	wire [7:0] fp_exp;
        ///	wire [22:0] fp_mantissa;
        ///	wire [FIXED_TOTAL_BIT-1-1:0] fx_number_without_sign;
        ///	assign {fx_sign, fp_exp, fp_mantissa} = fp_input;
        ///	
        ///	wire [31:0] aggregated = {1&apos;b1,fp_mantissa,8&apos;d0};
        ///	wire [7:0] shift_amnt = 8&apos;d127 - fp_exp - 1; // this -1 is for the extra 1
        ///	
        ///	wire [31:0] shifted_o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string float_to_fixed {
            get {
                return ResourceManager.GetString("float_to_fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module float_to_fixed_tb;
        ///
        ///	parameter FIXED_TOTAL_BIT = __TOTAL_BITS__;
        ///	reg [31:0] float_in;
        ///	
        ///	wire [FIXED_TOTAL_BIT-1:0] fixed_out;
        ///	
        ///	initial begin
        ///		$dumpfile(&quot;float_to_fixed.vcd&quot;);
        ///		$dumpvars(0, v);
        ///	end
        ///	integer fileHandle, dummyHandle;
        ///	integer fWriteHandle;
        ///	always @(fixed_out) begin
        ///	   #5 $fwrite(fWriteHandle,&quot;%b%b%b:%b\n&quot;, float_in[31], float_in[30:23],float_in[22:0], fixed_out);   
        ///	   //#5 $display(&quot;%b %b %b&lt;&gt;%b\n&quot;, float_in[31], float_in[30:23],float_in[22:0], fixed_out);   
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string float_to_fixed_tb {
            get {
                return ResourceManager.GetString("float_to_fixed_tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // shift &quot;in&quot; left until the most significant bit is a &quot;1&quot;
        ///// pass the shifted value, and number of shifts required
        ///// to the output.
        ///
        ///module scale_up (in,out,distance);
        ///
        ///parameter WIDTH = 16;
        ///parameter WIDTH_DIST = 4;
        ///
        ///input [WIDTH-1:0] in;
        ///output [WIDTH-1:0] out;
        ///output [WIDTH_DIST-1:0] distance;
        ///
        ///wire [(WIDTH_DIST+1) * WIDTH-1:0] shift_layers;
        ///assign shift_layers [WIDTH-1:0] = in;
        ///
        ///genvar i;
        ///generate
        ///	for (i=0;i&lt;WIDTH_DIST;i=i+1)
        ///	begin : shft
        ///		wire [WIDTH-1:0] layer_in;
        ///		wire [WID [rest of string was truncated]&quot;;.
        /// </summary>
        public static string scale_up {
            get {
                return ResourceManager.GetString("scale_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Status Will Show here....
        /// </summary>
        public static string Status_Default {
            get {
                return ResourceManager.GetString("Status_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Used two&apos;s complement from this WEB:&quot;http://www.ece.lsu.edu/ee3755/2012f/l05.v.html&quot;.
        /////Visit that for various efficient modules
        ///module twos_complement(minus_i,i);
        ///	parameter BITS = 32;
        ///	input [BITS-1:0] i;
        ///	output [BITS-1:0] minus_i;
        ///	
        ///	assign minus_i = -i;
        ///
        ///`ifdef NOT_THE_WAY_TO_DO_IT
        ///	// The methods below work but they are slightly less clear to a
        ///	// human reader and waste hardware and time unless the synthesis
        ///	// program realizes it&apos;s just negation.
        ///
        ///	assign        minus_i = 0 - i;  // [rest of string was truncated]&quot;;.
        /// </summary>
        public static string twos_comp {
            get {
                return ResourceManager.GetString("twos_comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fp2fx_data.txt.
        /// </summary>
        public static string V_Fp2Fx_Data {
            get {
                return ResourceManager.GetString("V_Fp2Fx_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fx2fp_out.txt.
        /// </summary>
        public static string V_Fp2Fx_Out {
            get {
                return ResourceManager.GetString("V_Fp2Fx_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fx2fp_data.txt.
        /// </summary>
        public static string V_Fx2Fp_Data {
            get {
                return ResourceManager.GetString("V_Fx2Fp_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fp2fx_out.txt.
        /// </summary>
        public static string V_Fx2Fp_Out {
            get {
                return ResourceManager.GetString("V_Fx2Fp_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __TOTAL_BITS__.
        /// </summary>
        public static string V_TOT_BITS {
            get {
                return ResourceManager.GetString("V_TOT_BITS", resourceCulture);
            }
        }
    }
}
